name: CI/CD Deploy Node.js App to EC2

on:
  push:
    branches: [ "master" ] # Tự động deploy khi push lên nhánh main
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup SSH key for EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem
          ssh-keyscan -H 47.129.216.11 >> ~/.ssh/known_hosts

      - name: Deploy Node.js app to EC2
        run: |
          ssh -i ~/.ssh/ec2_key.pem ubuntu@13.213.1.8 << 'EOF'
            cd goldenowl-devops-internship-challenge
            git pull origin main

           

            # Cài dependencies
            npm install

            # Dừng tiến trình cũ (nếu đang chạy)
            pkill node || true

            # Chạy lại server Node.js
            nohup npm start >/dev/null 2>&1 &
          EOF
